 export default [
    {
        name:'Linen Jacket Slim Fit',
        description:" Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton Shirt",
        image:'/img/cloths/cloth (1).png',
        price:150,
        category:"shirts",
        brand:"Shopam",
        rating:2,
        numReviews:4,
        countInStock:5,
        offerPrice:100,
    },
    {
        name:'Oxford Shirt Regular',
        description:" Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton Shirt",
        image:'/img/cloths/cloth (2).png',
        price:200,
        category:"shirts",
        brand:"Shopam",
        rating:2,
        numReviews:3,
        countInStock:8,
        offerPrice:120,

    },
    {
        name:'Plaid Cotton Shirt',
        image:'/img/cloths/cloth (3).png',
        description:" Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton Shirt",
        price:150,
        category:"shirts",
        brand:"Shopam",
        rating:4,
        numReviews:2,
        countInStock:5,
        offerPrice:50,

    },
    {
        name:'Plaid Cotton Shirt',
        description:" Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton Shirt",
        image:'/img/cloths/cloth (2).png',
        price:150,
        category:"shirts",
        brand:"Shopam",
        rating:6,
        numReviews:9,
        countInStock:2,
        offerPrice:130,
        
    },
    {
        name:'Plaid Cotton Shirt',
        description:" ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton ShirtPlaid Cotton Shirt",
        image:'/img/cloths/cloth (1).png',
        price:150,
        category:"shirts",
        brand:"Shopam",
        rating:3,
        numReviews:4,
        countInStock:0,
        offerPrice:0,
    }
]